# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: cicd

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: node:22-alpine

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma client
        run: npm run prisma:generate
      - name: Build project
        run: npm run build --if-present
      - name: Run Unit Tests
        run: npm test
  
  build-image:
    needs: unit-tests
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get package version
      id: get_version
      run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

    - name: Build and push Docker image with version
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: luskas8/orangebank-api:${{ steps.get_version.outputs.VERSION }}
        file: ./build/docker/Dockerfile.prod
