# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: deploy

on:
  push:
    branches: [ "master" ]
  workflow_run:
    workflows: ["cicd"]
    types:
      - completed
  workflow_dispatch:

jobs:
  # apply-migrations:
  #   environment: manual-deploy
  #   runs-on: ubuntu-latest
  #   container: node:22-alpine
  #   env:
  #     DATABASE_URL: ${{ secrets.DATABASE_URL }}

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Apply Prisma migrations
  #       run: npm run prisma:migrate

  deploy:
    runs-on: ubuntu-latest
    needs: apply-migrations
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get package version
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Deploy on Render
        env:
          hook_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          docker_url: docker.io/luskas8/orangebank-api:${{ steps.get_version.outputs.VERSION }}
        run: curl "$hook_url&imgURL=$docker_url"
